# Generated by Django 5.1.2 on 2024-10-25 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("statsbomb_id", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("statsbomb_id", models.IntegerField()),
                ("date", models.DateTimeField()),
                ("home_goals", models.IntegerField()),
                ("away_goals", models.IntegerField()),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_matches",
                        to="match_viewer.team",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_matches",
                        to="match_viewer.team",
                    ),
                ),
            ],
        ),
    ]
